dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
before_install:
    - cd sandwich-shop-manager
after_success:
    - mvn jacoco:report coveralls:report
cache:
directories:
- $HOME/.m2
script:
- mvn clean install